### ISSUE TITLE
Erro start e solução no Windows com Docker Toolbox

### ISSUE THREAD

**Issue by MarcosJRcwb** [CodeForCuritiba/datascience-kit#4]
Ao tentar rodar conforme o comando enunciado para windows, estava apresentando o o erro: 
$ docker run -v $(pwd):/app --rm -it -p 8888:8888 code4cwb/datascience-kit
C:\Program Files\Docker Toolbox\docker.exe: invalid reference format: repository
 name must be lowercase.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

Após pesquisar em alguns sites, localizei a correção acrescentando as aspas para:

docker run -v "$(pwd):/app" --rm -it -p 8888:8888 code4cwb/datascience-kit

**Comment by joepreludian** [comment]
Você tem como executar o comando novamente e testar se você consegue ver os arquivos da sua pasta atual ao rodar o container? Aquele parâmetro -v faz o link da pasta onde você está executando o Docker dentro do container.

**Comment by MarcosJRcwb** [comment]
![image](https://user-images.githubusercontent.com/28488539/71609163-1d362380-2b65-11ea-95d1-5f15939f2cb1.png)

Este é o status após inserir as aspas no comando.

**Comment by joepreludian** [comment]
Certo. Ao rodar o segundo comando, você consegue abrir o browser na porta 8888? Consegue enxergar os arquvios da pasta onde você está executando o comando? (No caso o /c/Program Files/Docker Toolbox? 

Caso consiga ver, sinal que o comando está rodando normalmente no windows.

**Comment by joepreludian** [comment]
Também realizei uns testes aqui e o ato de escapar os caracteres com áspas deu certo. Atente-se que ele só vai permitir a montagem caso a pasta esteja dentro do /c/User:

https://stackoverflow.com/questions/34161352/docker-sharing-a-volume-on-windows-with-docker-toolbox

Marcarei essa issue como respondida.
